#!/usr/bin/env bash

./runint.sh -a tests/hello.js
./runint.sh -a tests/hello2.js
./runint.sh -a tests/stmt_for.js
./runint.sh -a tests/stmt_for2.js
./runint.sh -a tests/stmt_for_break.js
./runint.sh -a tests/stmt_for_break2.js
./runint.sh -a tests/stmt_for_break3.js
./runint.sh -a tests/stmt_for_continue.js
./runint.sh -a tests/stmt_for_continue2.js
./runint.sh -a tests/stmt_for_continue3.js
./runint.sh -a tests/stmt_return_break.js
./runint.sh -a tests/stmt_switch.js
./runint.sh -a tests/stmt_while.js
./runint.sh -a tests/stmt_throw.js
./runint.sh -a tests/expr_call.js
./runint.sh -a tests/expr_new.js
./runint.sh -a tests/expr_array.js
./runint.sh -a tests/expr_assign.js
./runint.sh -a tests/expr_assign2.js
./runint.sh -a tests/expr_assign3.js
./runint.sh -a tests/expr_cond.js
./runint.sh -a tests/expr_delete_prop.js
./runint.sh -a tests/expr_delete_prop_computed.js
./runint.sh -a tests/expr_fun.js
./runint.sh -a tests/expr_fun2.js
./runint.sh -a tests/expr_incdec.js
./runint.sh -a tests/clazz.js
./runint.sh -a tests/alength.js
./runint.sh -a tests/scope4.js
./runint.sh -a tests/scope1.js
./runint.sh -a tests/expr_arguments1.js
./runint.sh -a tests/sunspider/access-binary-trees.js
./runint.sh -a tests/sunspider/access-nbody.js
./runint.sh -a tests/sunspider/3d-cube.js
./runint.sh -a tests/sunspider/3d-morph.js
./runint.sh -a tests/test262/test/language/expressions/addition/S11.6.1_A2.1_T1.js
