/* 
 * Copyright 2014-2016 Samsung Research America, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Declare property tables for some JS / DOM primitives.
 * The indirection maps must be computed and generated by the compiler based on the other
 * code being linked in, but the tables themselves, and the operations that
 * they refer to, are here.
 *
 * Note that in wrapping flat properties of DOM objects, we must generate setters and getters
 * here, since each access to them will require round-tripping to the DOM through the FFI
 * boundary.
 */

#ifndef __SJS_FFI
#define __SJS_FFI

#include <runtime.h>

#ifdef FALSE
extern object_t __ffi_document;

extern object_t __ffi_htmlelement;
#endif

extern object_t __ffi_console;

extern object_t __ffi_object_proto;

#endif //__SJS_FFI
